
doctrine_mongodb:
    connections:
        default:
            server: 'mongodb://localhost:27017'  # URL de ton serveur MongoDB
            options: {}
    default_database: 'vimana_agence'  # Nom de ta base de données MongoDB

    document_managers:
        default:
            auto_mapping: true
            mappings:
                App\Document:
                    type: attribute   # Spécifie le type de mappage
                    dir: '%kernel.project_dir%/src/Document'  # Dossier où sont stockés tes documents MongoDB
                    prefix: 'App\Document'  # Le namespace de tes documents

