parameters:
    BREVO_API_KEY: '%env(BREVO_API_KEY)%'  # Ajoute la variable d'environnement pour la clé API

services:
    _defaults:
        autowire: true      # Automatically inject dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # App\Service\BrevoMailer configuration
    App\Service\BrevoMailer:
        arguments:
            $client: '@http_client'  # Inject Symfony's HTTP client into your service

